#!/usr/bin/env python3
"""
Comprehensive Email Configuration Verification
Tests OTP and weekly report email functionality for local and production
"""
import sys
import os

# Add app directory to Python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

def verify_email_config():
    """Verify email configuration in current environment"""
    print("=== EMAIL CONFIGURATION VERIFICATION ===")
    
    from app import create_app
    
    app = create_app()
    
    with app.app_context():
        # Get email configuration
        config = {
            'MAIL_SERVER': app.config.get('MAIL_SERVER'),
            'MAIL_PORT': app.config.get('MAIL_PORT'),
            'MAIL_USE_TLS': app.config.get('MAIL_USE_TLS'),
            'MAIL_USERNAME': app.config.get('MAIL_USERNAME'),
            'MAIL_PASSWORD': app.config.get('MAIL_PASSWORD'),
            'MAIL_DEFAULT_SENDER': app.config.get('MAIL_DEFAULT_SENDER'),
            'ADMIN_EMAIL': app.config.get('ADMIN_EMAIL')
        }
        
        print("Current Email Configuration:")
        for key, value in config.items():
            if 'PASSWORD' in key and value:
                print(f"  {key}: {'SET' if value else 'NOT SET'}")
            else:
                print(f"  {key}: {value}")
        
        # Check configuration completeness
        required_fields = ['MAIL_SERVER', 'MAIL_USERNAME', 'MAIL_PASSWORD']
        missing_fields = [field for field in required_fields if not config.get(field)]
        
        if missing_fields:
            print(f"\nMissing required fields: {missing_fields}")
            return False, config
        else:
            print(f"\nEmail configuration: COMPLETE")
            return True, config

def test_otp_email_service():
    """Test OTP email service functionality"""
    print("\n=== OTP EMAIL SERVICE TEST ===")
    
    from app import create_app
    app = create_app()
    
    with app.app_context():
        try:
            from app.services.otp_service import OTPService
            from app.services.email_service import EmailService
            
            # Test OTP generation (without sending)
            print("Testing OTP generation...")
            test_email = "test@example.com"
            otp_result = OTPService.generate_otp(test_email)
            otp_code = otp_result[0] if isinstance(otp_result, tuple) else otp_result
            email_sent = otp_result[1] if isinstance(otp_result, tuple) else False
            print(f"OTP generated: {otp_code}")
            print(f"Email sent: {'YES' if email_sent else 'NO'}")
            
            # Test OTP verification
            print("Testing OTP verification...")
            verified = OTPService.verify_otp(test_email, otp_code)
            print(f"OTP verification: {'SUCCESS' if verified else 'FAILED'}")
            
            # Test email service configuration check
            print("Testing email service configuration...")
            # This should NOT show "Email configuration incomplete" warning
            result = EmailService.send_email(
                to="test@example.com",
                subject="OTP Test - College Virtual Assistant",
                body="This is a test OTP email to verify configuration.\n\nOTP: 123456\n\nTest email sent at: Just now"
            )
            print(f"Email service test result: {'SUCCESS' if result else 'FAILED'}")
            
            return True
            
        except Exception as e:
            print(f"OTP email service test error: {e}")
            return False

def test_weekly_report_email():
    """Test weekly report email functionality"""
    print("\n=== WEEKLY REPORT EMAIL TEST ===")
    
    from app.services.email_service import EmailService
    
    try:
        # Test weekly report email content
        print("Testing weekly report email content...")
        
        weekly_report_content = """
        WEEKLY ANALYTICS REPORT - College Virtual Assistant
        
        Generated at: Just now
        
        SYSTEM STATISTICS:
        - Total Students: 150
        - Total Faculty: 25
        - Total Notifications: 45
        - Active Notifications: 12
        - Total Complaints: 8
        - Pending Complaints: 3
        - Total Results: 200
        
        CHATBOT ACTIVITY:
        - Total Queries: 1,250
        - Unknown Queries: 45
        - Result Queries: 320
        - Fee Queries: 180
        
        EMAIL NOTIFICATIONS:
        - OTP Emails Sent: 25
        - Weekly Reports Sent: 1
        
        SYSTEM HEALTH:
        - Database: Connected
        - Email Service: Active
        - Chatbot Service: Active
        - Last Backup: 2 days ago
        
        This is an automated report generated by College Virtual Assistant.
        For detailed analytics, visit the admin dashboard.
        """
        
        # Test email service with weekly report content
        from app import create_app
        app = create_app()
        
        with app.app_context():
            result = EmailService.send_email(
                to="admin@example.com",
                subject="Weekly Analytics Report - College Virtual Assistant",
                body=weekly_report_content
            )
            print(f"Weekly report email test result: {'SUCCESS' if result else 'FAILED'}")
            
        return True
        
    except Exception as e:
        print(f"Weekly report email test error: {e}")
        return False

def verify_production_config():
    """Verify production (Render) configuration"""
    print("\n=== PRODUCTION CONFIGURATION VERIFICATION ===")
    
    # Check render-docker.yaml configuration
    render_config_file = os.path.join(os.path.dirname(__file__), 'render-docker.yaml')
    
    if os.path.exists(render_config_file):
        print("Checking render-docker.yaml configuration...")
        
        with open(render_config_file, 'r') as f:
            content = f.read()
            
        # Check for email configuration in render-docker.yaml
        email_configs = []
        lines = content.split('\n')
        for line in lines:
            if 'MAIL_' in line and 'value:' in line:
                email_configs.append(line.strip())
        
        print("Email configuration in render-docker.yaml:")
        for config in email_configs:
            if 'PASSWORD' in config:
                print(f"  {config.split(':')[0].strip()}: SET")
            else:
                print(f"  {config}")
        
        # Check if critical email fields are configured with actual values (not placeholders)
        critical_fields = ['MAIL_USERNAME', 'MAIL_PASSWORD', 'MAIL_DEFAULT_SENDER']
        configured_fields = []
        
        for field in critical_fields:
            field_pattern = f"- key: {field}\n        value:"
            if field_pattern in content:
                # Extract the value to check if it's a placeholder
                field_index = content.find(field_pattern)
                if field_index != -1:
                    value_line = content[field_index:field_index + 200].split('\n')[1]
                    value = value_line.split('value:')[1].strip() if 'value:' in value_line else ''
                    
                    if value and not value.startswith('your-') and not value.startswith('UPDATE_'):
                        configured_fields.append(field)
        
        if len(configured_fields) == len(critical_fields):
            print("Production email configuration: COMPLETE")
            return True
        else:
            missing = set(critical_fields) - set(configured_fields)
            print(f"Missing or placeholder production fields: {missing}")
            return False
    else:
        print("render-docker.yaml file not found")
        return False

def verify_local_config():
    """Verify local configuration"""
    print("\n=== LOCAL CONFIGURATION VERIFICATION ===")
    
    # Check .env file
    env_file = os.path.join(os.path.dirname(__file__), '.env')
    
    if os.path.exists(env_file):
        print("Checking .env file...")
        
        with open(env_file, 'r') as f:
            content = f.read()
            
        # Check for email configuration in .env
        email_configs = []
        lines = content.split('\n')
        for line in lines:
            if line.startswith('MAIL_') and '=' in line:
                email_configs.append(line.strip())
        
        print("Email configuration in .env:")
        for config in email_configs:
            if 'PASSWORD' in config:
                print(f"  {config.split('=')[0]}: SET")
            else:
                print(f"  {config}")
        
        # Check if critical email fields are configured
        critical_fields = ['MAIL_SERVER', 'MAIL_USERNAME', 'MAIL_PASSWORD', 'MAIL_DEFAULT_SENDER']
        configured_fields = []
        
        for field in critical_fields:
            if f"{field}=" in content:
                configured_fields.append(field)
        
        if len(configured_fields) == len(critical_fields):
            print("Local email configuration: COMPLETE")
            return True
        else:
            missing = set(critical_fields) - set(configured_fields)
            print(f"Missing local fields: {missing}")
            return False
    else:
        print(".env file not found")
        return False

def main():
    """Main verification function"""
    print("COMPREHENSIVE EMAIL CONFIGURATION VERIFICATION")
    print("=" * 60)
    
    results = {
        'local_config': False,
        'production_config': False,
        'email_config_complete': False,
        'otp_service': False,
        'weekly_report': False
    }
    
    try:
        # Verify local configuration
        results['local_config'] = verify_local_config()
        
        # Verify production configuration
        results['production_config'] = verify_production_config()
        
        # Verify email configuration
        config_complete, config_data = verify_email_config()
        results['email_config_complete'] = config_complete
        
        if config_complete:
            # Test OTP email service
            results['otp_service'] = test_otp_email_service()
            
            # Test weekly report email
            results['weekly_report'] = test_weekly_report_email()
        
        print("\n" + "=" * 60)
        print("VERIFICATION RESULTS SUMMARY")
        print("=" * 60)
        
        for test, result in results.items():
            status = "PASS" if result else "FAIL"
            print(f"{test.replace('_', ' ').title()}: {status}")
        
        # Overall status
        all_passed = all(results.values())
        print(f"\nOverall Status: {'ALL TESTS PASSED' if all_passed else 'SOME TESTS FAILED'}")
        
        if not all_passed:
            print("\nISSUES FOUND:")
            for test, result in results.items():
                if not result:
                    print(f"  - {test.replace('_', ' ').title()}: FAILED")
        
        print("\nRECOMMENDATIONS:")
        if not results['local_config']:
            print("  - Update .env file with complete email configuration")
        if not results['production_config']:
            print("  - Update render-docker.yaml with complete email configuration")
        if not results['email_config_complete']:
            print("  - Check environment variable loading")
        if not results['otp_service']:
            print("  - Verify OTP service configuration")
        if not results['weekly_report']:
            print("  - Verify weekly report email content")
        
        return all_passed
        
    except Exception as e:
        print(f"Verification error: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
